# action.yml
name: 'publish_app'
description: 'Update the revision of an app in the GitOps repo'
inputs:
  project:
    description: 'GitHub project name to deploy'
    required: true
  tag:
    description: 'Tag of built container image'
    required: true
  serial_number:
    description: 'Serial number to prevent overwriting newer images'
    required: true
  container_index:
    description: 'Container number to update'
    required: false
    default: 0
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.tag }}
    - ${{ inputs.serial_number }}
    - ${{ inputs.container_index }}
