# action.yml
name: "publish_app"
description: "Update the revision of an app in the GitOps repo"
inputs:
  projects:
    description: "comma separated list of projects to deploy image tags to"
    required: true
  tag:
    description: "Override tag of built container image"
    required: false
  branch:
    description: "Branch being deployed"
    required: true
  serial_number:
    description: "Override serial number to prevent overwriting newer images"
    required: false
  container_index:
    description: "Container number in Pod to update (default 0)"
    required: false
    default: 0
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.projects }}
    - ${{ inputs.tag }}
    - ${{ inputs.serial_number }}
    - ${{ inputs.container_index }}
    - ${{ inputs.branch }}
