# action.yml
name: "publish_app"
description: "Update the revision of an app in the GitOps repo"
inputs:
  projects:
    description: "Comma separated list of projects to deploy image tags to"
    required: true
  tag:
    description: "Override tag of built container image"
    required: false
  environments:
    description: "Comma separated list of environments to deploy image tags to"
    required: true
  serial_number:
    description: "Override serial number to prevent overwriting newer images"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.projects }}
    - ${{ inputs.tag }}
    - ${{ inputs.serial_number }}
    - ${{ inputs.environments }}
