name: Build Docker Image
on:
  push:

jobs:
  push:
    concurrency:
      group: ${{ github.event_name }}-${{ github.ref_name == 'main' && github.sha || github.ref_name }}-build
      cancel-in-progress: true
    name: build and push image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    env:
      ECR_REPOSITORY: publish_app
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@380f3a50f5896345ce3f2dd3ba2d821c030f17d8 # v3
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GithubActions-publish-app-ci

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@2fc7aceee09e9e4a7105c0d060c656fad0b4f63d # v1

      - name: "Calculate Image ID & Version"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Strip git ref prefix from version
          IMAGE_ID=$(echo "$ECR_REGISTRY/$ECR_REPOSITORY" | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Build Production OCI Image
        run: |
          docker pull $IMAGE_ID:latest || true
          docker build --cache-from $IMAGE_ID:latest \
          --build-arg DOCKER_ECR=${{ secrets.DOCKER_ECR }} \
          --build-arg RELEASE_VERSION=${IMAGE_TAG} \
          -t $IMAGE_ID:latest .

      - name: Push to ECR
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          docker push $IMAGE_ID:latest
