name: Build Docker Image
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  issue_comment:
    types: [created]
jobs:
  push:
    concurrency:
      group: ${{ github.event.comment.id }}-${{ github.event_name }}-${{ ( github.ref_name == 'master' || github.ref_name == 'main' ) && github.sha || github.ref_name }}-build
      cancel-in-progress: true
    name: Test, build and push image
    permissions:
      id-token: write
      contents: read
      statuses: write
      issues: read
      pull-requests: write
    secrets: inherit
    uses: ausaccessfed/workflows/.github/workflows/deploy-sync.yml@main
    with:
      ecr_repository: publish_app
      version_command: echo ""
      event_name: ${{ github.event_name }}
      test_environments: ''
      default_branch: main
      platforms: "['linux/arm64','linux/amd64']"
      production_environments: ''
      development_environments: ''
